spring:
  datasource:
    url: jdbc :mysql://${DATABASE_HOST:localhost} :${DATABASE_PORT :3307}/${DATABASE_NAME:dbbituin}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
  messages:
    basename: i18n/messages

jwt:
  secret-key: bituinDestinations_SecureJwtKey_2025_IT342_Project_Key
  expiration-time: 86400000